disabled_rules:
  - unused_optional_binding

opt_in_rules:
  - file_header
  - indentation_width

file_length: 660
function_parameter_count: 10
function_body_length: 100
line_length: 250

identifier_name:
  allowed_symbols: ["_"]
  max_length: 50
  excluded:
    - id
    - in

trailing_whitespace:
  ignores_empty_lines: true
